#ifndef VTEKINTERFACE_GLOBAL_H
#define VTEKINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VTEKINTERFACE_LIBRARY)
#  define VTEKINTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define VTEKINTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#define TOGGLE_BUTTON_NORMAL 1
#define TOGGLE_BUTTON_REVERSED 0


#endif // VTEKINTERFACE_GLOBAL_H
