#ifndef CUSTOMFRAME_GLOBAL_H
#define CUSTOMFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CUSTOMFRAME_LIBRARY)
#  define CUSTOMFRAMESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CUSTOMFRAMESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CUSTOMFRAME_GLOBAL_H
