#ifndef ADDRDEFINE_H
#define ADDRDEFINE_H

#define SLEEP(delay) QThread::currentThread()->msleep(delay);


//0x12c4
//0xea12
#define QUAD_VENDOR_ID 0x0490
#define QUAD_PRODUCT_ID  0x5747
#define FBL_VENDOR_ID 0x10c4
#define FBL_PRODUCT_ID  0xea60

#define _READ 0
#define _WRITE 1

#define HARDWARE_ADDR 1
#define HARDWARE_VALUE 1
#define SOFTWARE_ADDR 2
#define SERIAL_NUM_ADDR 3

#define READ_STRING 1
#define READ_BYTE 2
#define READ_NONE 3

#define DEFAULT_BAUDRATE 115200

#define TIMEOUT_TO_WRITE 15

#define RX_MONITOR_WIDTH 210
#define RX_MONITOR_HEIGHT 210
#define RX_SENSOR_WIDTH 16
#define RX_SENSOR_HEIGHT 16

#define BIND_ADDR 102
#define RXTYPE_ADDR 126
#define THROTLE_MIN_ADDR 127
#define THROTLE_MAX_ADDR 128
#define RXCENTER_ADDR 129
#define TX_MODE_ADDR 130

#define RXCENTER_VAL 1

#define RX_TRADITION_VAL 1
#define RX_PPM_VAL 3
#define RX_SBUS_VAL 2
#define RX_DSM2_VAL 4
#define RX_DSMX_VAL 5
#define RX_JR_XBUS_VAL 6

#define TX_MODE_1 1
#define TX_MODE_2 2
#define TX_MODE_3 3
#define TX_MODE_4 4

#define FLYMODE1_ADDR 121
#define FLYMODE2_ADDR 122
#define FLYMODE3_ADDR 123
#define FLYMODE4_ADDR 124
#define FLYMODE5_ADDR 125

#define FLYMODE1_VAL 1
#define FLYMODE2_VAL 2
#define FLYMODE3_VAL 3
#define FLYMODE4_VAL 4
#define FLYMODE5_VAL 5
#define FLYMODE6_VAL 6
#define FLYMODE7_VAL 7

#define FLYMODE1_TEXT "Manual"
#define FLYMODE2_TEXT "Altitude"
#define FLYMODE3_TEXT "GPS"
#define FLYMODE4_TEXT "GPS No Altitude"
#define FLYMODE5_TEXT "GPS-Smart"
#define FLYMODE6_TEXT "Go Home"
#define FLYMODE7_TEXT "Loiter"

#define RX_ALE_ADDR 111
#define RX_ELE_ADDR 112
#define RX_RUDDER_ADDR 114
#define RX_THROTLE_ADDR 113
#define RX_GEAR_ADDR 115
#define RX_AUX1_ADDR 117
#define RX_PITCH_ADDR 116

#define SENSOR_ROLL_ANGLE_ADDR 501
#define SENSOR_PITCH_ANGLE_ADDR 502
#define SENSOR_YAW_ANGLE_ADDR 503
#define CALIB_ACC_STATUS_ADDR 510
#define CALIB_MAG_STATUS_ADDR 511

#define I2C_ERROR_ADDR 508
#define GPS_STATUS_ADDR 600

#define FRAME_TYPE_ADDR 201
#define FRAME_SIZE_ADDR 202
#define IMU_MOUNT_X 203
#define IMU_MOUNT_Y 204
#define IMU_MOUNT_Z 205
#define GPS_MOUNT_X 206
#define GPS_MOUNT_Y 207
#define GPS_MOUNT_Z 208
#define IDLE_MOTORSPEED_ADDR 209

#define FRAME_TYPE_QUADX 1
#define FRAME_TYPE_QUADPLUS 2
#define FRAME_TYPE_HEXX 3
#define FRAME_TYPE_HEXPLUS 4
#define FRAME_TYPE_HEXY 8
#define FRAME_TYPE_HEXV 7
#define FRAME_TYPE_OCTOX 5
#define FRAME_TYPE_OCTOPLUS 6
#define FRAME_TYPE_OCTOQUAD 9

#define FRAME_SIZE_SMALL 1
#define FRAME_SIZE_MEDIUM 2
#define FRAME_SIZE_LARGE 3
#define FRAME_SIZE_XLARGE 4
#define FRAME_SIZE_XXLARGE 5

#define FAILSAFE_ACTION_ADDR 403
#define GOHOME_SPEED_ADDR 401

#define VBAT_ADDR 422
#define NUMBER_OF_CELL_ADDR 423
#define PERCENT_BAT_ADDR 425

#define VALARM_1_ADDR 426
#define VALARM_2_ADDR 427
#define VALARM_3_ADDR 428

#define MIN_ALT_GOHOME_ADDR 400

#define FAILSAFE_ACTION_GOHOME 3
#define FAILSAFE_ACTION_LANDING 1
#define FAILSAFE_ACTION_GOHOME_HOLD 4
#define FAILSAFE_ACTION_LANDING_HOLD 2

#define GAIN_ROLL_ADDR 301
#define GAIN_PTCH_ADDR 302
#define GAIN_YAW_ADDR 303
#define GAIN_VER_ADDR 304
#define GAIN_GPS_ADDR  305
#define AGILITY_ADDR 306
#define YAW_RATE_ADDR 307

#define GIMBAL_ONOFF_ADDR 550
#define GIMBAL_REV_ROLL 551
#define GIMBAL_REV_PITCH 552
#define GIMBAL_REV_CONTROL_PITCH 554
#define GIMBAL_GAIN_ROLL 555
#define GIMBAL_GAIN_PITCH 556
#define GIMBAL_CENTER_ROLL 557
#define GIMBAL_CENTER_PITCH 558

#define GIMBAL_ON_VAL 1
#define GIMBAL_OFF_VAL 0

#define ERROR_ADDR  999

#define DARK_SKIN 1
#define GREY_SKIN 0

#   define WMI_STATUS_PLUGGED 2
#   define WMI_STATUS_UNPLUGGED 3

#endif // ADDRDEFINE_H
