#ifndef DRAWIMAGESPOS_GLOBAL_H
#define DRAWIMAGESPOS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DRAWIMAGESPOS_LIBRARY)
#  define DRAWIMAGESPOSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DRAWIMAGESPOSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DRAWIMAGESPOS_GLOBAL_H
